### ISSUE TITLE
Feature:  Add caseinsensitive Handling for wildcard searches in SearchBuilder

### ISSUE THREAD

**Issue by eppinger** [coldbox-modules/cbelasticsearch#106]
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-wildcard-query.html

**Comment by eppinger** [comment]
What is your philosophy regarding Elasticsearch version specific features ?

Can I implement this feature based on the "versionTarget" setting ?

**Comment by jclausen** [comment]
@eppinger Since we have dropped support for ES version 6,  your original code commits work and I have added those to the repo.
