### ISSUE TITLE
slf4j is missing if not using commandbox

### ISSUE THREAD

**Issue by eppinger** [coldbox-modules/cbelasticsearch#12]
If you use a native tomcat/lucee install this lib is missing.

Could you add the lib again ?

Thanks

**Comment by jclausen** [comment]
@eppinger : Which version of Lucee?  The conflict in the two implementations wasn't an issue with just CommandBox.  It was being seen on a 4.x version of Lucee.

**Comment by eppinger** [comment]
sorry for the late reply

Lucee 5.2.7.63

**Comment by eppinger** [comment]
this issue is still existing with a Lucee 5.2.9.31 / Tomcat Installation

Could you add the jar back in a folder "additional jars"  and add a note in the readme ?

**Comment by jclausen** [comment]
Yes. I'll see if I can find a workaround to only load it when it's not in the existing classpath.

**Comment by jclausen** [comment]
This is resolved with commit `0e213ad`, which will be available in the 1.3.0 release, out later today
