### ISSUE TITLE
Add track_total_hits property

### ISSUE THREAD

**Issue by davidsf** [coldbox-modules/cbelasticsearch#125]
The total response of a query (I think since version 7), set a struct like:

```
"hits": { 
    "total": {
      "value": 10000,
      "relation": "gte"
    },
...
``` 
Sometimes we need the real total value, not the estimation.

The are a `track_total_hits` property to the query [Elasticsearch doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-your-data.html#track-total-hits) that when set to `true` it tracks the correct total:

```
"total": 
      "value": 2734635,
      "relation": "eq"
    }
```

(it's posible to set to a number too, see the docs)

**Comment by jclausen** [comment]
@davidsf If you install `cbelasticsearch@3.1.0`   there is a new `set` method available on the `SearchBuilder` to set top-level values of the outbound query. 

The issue you are running in to has to do with this change in ES v7+ https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#paginate-search-results

So, with 3.1.0 you can simple do  `searchBuilder.set( "track_total_hits", true )` and it will add that property to the outbound payload to ES.
