### ISSUE TITLE
addMapping method missing from IndexBuilder.cfc?

### ISSUE THREAD

**Issue by malik415** [coldbox-modules/cbelasticsearch#13]
In the documentation shown here: https://github.com/coldbox-modules/cbox-elasticsearch

You have this line:  

// add the mapping and save
indexBuilder.addMapping( "books", booksMapping ).save();

Maybe I am missing something, but I do not see the "addMapping" method in this class and when I run the code I also get an error indicating this method does not exist.  I am running CF 11 via CommandBox.

Any ideas?

**Comment by jclausen** [comment]
Hi Malik.  Looks like that was an old version of the documentation.  I will correct that now. The new syntax is:

```
indexBuilder.new( 'books', booksMapping ).save()
```

**Comment by jclausen** [comment]
Actually, this a bit more complex that that.  In Elasticsearch 6, the "type" has been deprecated and will only allow one per index in the future, as a convenience for backwards compatibility.  As a result, I've updated to the README to remove the second option to append a type mapping.  I need to push a release in the next week, so I'll update the rest of the docs to reflect not using types in mappings, going forward.

**Comment by malik415** [comment]
Thanks, it also seems that the "string" type is no longer being used or is being deprecated and should be replaced with "text".

Example:  	"title" : {"type":"string"},
		       "summary" : {"type":"string"}

should now I *think* be:

Updated:  	"title" : {"type":"text"},
		       "summary" : {"type":"text"}
