### ISSUE TITLE
Connect to various elasticsearch clusters

### ISSUE THREAD

**Issue by davidsf** [coldbox-modules/cbelasticsearch#17]
We have two elasticsearch clusters (one with user data and another with stats). 

As I see, the module only can connect to one cluster, correct? 

Can I use the module to connect to two clusters?

**Comment by jclausen** [comment]
I know we corresponded on Slack regarding this, but just wanted to post a comment that this is still on our radar.  It's a pretty big architectural change for the module/configuration though, so it's slated for a major release.

**Comment by jclausen** [comment]
While not natively supported in the module, Commit #b239c716 implements changes in the instantiation and object usage of the model which support the ability to create additional clients to connect to non-primary clusters.  Documentation for this procedure may be found here:  https://github.com/coldbox-modules/cbox-elasticsearch/blob/development/docs/Configuration.md#connection-to-secondary-elasticsearch-clusters

I'm going to close this one out, but please know that multi-cluster native configuration is on our roadmap for a 2.0, major release.
