### ISSUE TITLE
returnvalue in jestClient newResult() ?

### ISSUE THREAD

**Issue by eppinger** [coldbox-modules/cbelasticsearch#27]
Should this not be "searchResult" instead of "Document" in the newResult() function

````
	/**
	* SearchResult provider
	**/
	Document function newResult() provider="SearchResult@cbElasticsearch"{}
	
	/**
	* Configure instance once DI is complete
	**/
	any function onDIComplete(){

		configure();

	}
````

**Comment by jclausen** [comment]
Yes.  Good catch. Most likely the reason it hasn't been caught is because Wirebox's overwrites the function when it creates the provider version.

I've pushed a fix for this return type up to development.
