### ISSUE TITLE
elasticSearch Logbox Appender

### ISSUE THREAD

**Issue by eppinger** [coldbox-modules/cbelasticsearch#30]
this will break ES >6

`		
instance.DEFAULTS = {
			"index"            : "logbox", 
			"type"             : "logs-" & dateFormat( now(), "yyyy-mm-dd" ), 
			"rotate"           : true, 
			"rotationDays"     : 30,
			"rotationFrequency": 5,
			"ensureChecks"     : true,
			"autoCreate"       : true
		};
`

In ES > 6 is only one Type per Index allowed. 

I think it would be better to set:
`
"index" : "logs-" & dateFormat( now(), "yyyy-mm-dd" )",
"type" : "logbox"
`

**Comment by jclausen** [comment]
Good catch @eppinger ! I'm thinking maybe we need to eliminate the date in the index name completely, though, as cross-index work in ES is a pain.  I will probably just standardize to use the application name as the index name.

**Comment by jclausen** [comment]
The `type` key was removed from the defaults in v1.2.0, which updated the module to provide ES7 compatibility.  Closing this as resolved.
