### ISSUE TITLE
Support method chaining from Document.setValue()?

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/cbelasticsearch#40]
If the `Document.setValue()` function returned `true` as opposed to nothing (`void`), we could chain multiple `setValue()` calls together:

```js
var myDoc = getInstance( "Document@cbElasticSearch" )
    .new(
        index = "my_index"
        type = "_doc"
    )
    .setValue( "name", "Fred" )
    .setValue( "age", "89" )
    .setValue( "isMember", true )
    .save();
```

The `populate()` method returns the initialized Document, so it seems this is already an established precedent?

**Comment by michaelborn** [comment]
Happy to send up a PR if necessary.

**Comment by jclausen** [comment]
That’s a good call. Please do! :)

**Comment by jclausen** [comment]
Actually the whole document API is kind of a mess and could use a second look.  This is primarily a product of existing use ( I can’t remember the last time I used the setValue method ). Feel free to take liberties in your PR with any additional methods that might be handy - e.g. a merge() method.

**Comment by michaelborn** [comment]
I don't feel confident enough with the ES API to "take liberty" with it, but I will try to add a few more tests for the Document model, since I see the `setValue()` method isn't currently tested.
