### ISSUE TITLE
Support method chaining from filterTerm, filterTerms

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/cbelasticsearch#43]
Both of these search builder fields do not return anything, and thus contradict the standard SearchBuilder api.

* `filterTerm( name, value )`
* `filterTerms( array name, array value )`

I can push up a PR for this as well, provided we agree it's a good fix.

**Comment by jclausen** [comment]
Agreed.  Both of these should return `this`.  I'm pushing a release today, so I can take those while I am in there.
