### ISSUE TITLE
Add support for updating index settings

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/cbelasticsearch#48]
It would be really nice if we had the ability to programmatically update index settings from CFML (without using Postman). Right now the `JestClient` `ApplyIndex()` function definitely only supports creating *new* indices.

I believe this is the class we need to utilize:

https://github.com/searchbox-io/Jest/blob/fe19dc4396e08f0e03c4e749a60b8a0ed398f084/jest-common/src/main/java/io/searchbox/indices/settings/UpdateSettings.java

Then any of these settings could be supported using a key/value struct:

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html#indices-update-settings

I intend to take a crack at this at some point.

FYI, I'm highly interested in this to improve write performance during a mass-serialization on startup.

e.g. issue this call before mass-inserting documents

```
PUT /content/_settings
{
    "index" : {
        "refresh_interval" : "-1"
    }
}
```

And of course issue a reversal afterwards.

**Comment by jclausen** [comment]
The applyMapping function in the client can be used to update the mapping presently.  It could definitely be expanded, though.

________________________________

**Comment by michaelborn** [comment]
I was more interested in changing index settings, like `refresh_interval`,
than in modifying the mapping.

**Comment by jclausen** [comment]
You can still use the index builder to do this:

```
indexBuilder.setSettings( 
  { 
   "index" : {
        "refresh_interval" : "-1"
     }
  } 
);
indexBuilder.save();
```

If no mappings are provided, they will not be applied.
