### ISSUE TITLE
Aggregation only Querys doesn't support the setMaxrows() anymore

### ISSUE THREAD

**Issue by eppinger** [coldbox-modules/cbelasticsearch#49]
This is caused by the commit 3459d8d98c79360567cfdf97bc67fa0957ebc96a

If i only want to aggregate, i have no query. In my opinion "from" and "size" could take the defaults. and are not dependant to the query

```
       if ( !isNull( variables.query ) && !structIsEmpty( variables.query ) ) {
            dsl[ "query" ] = variables.query;
        }
        
        dsl[ "from"] = variables.startRow;
        dsl[ "size" ] = variables.maxRows;
```

**Comment by eppinger** [comment]
and additional could we implement an alias "size" for maxRows like in the ES-DSL ?

**Comment by jclausen** [comment]
The `dsl.size` , when provided, was blowing up on ES 6x, which is why it was omitted with aggregations,  Let me take another pass at it to see what we can do.

**Comment by jclausen** [comment]
This should be resolved in the current release.  If you are performing an aggregation only query, you can run `setMaxRows( 0 )` to prevent any hits from returing.
