### ISSUE TITLE
[docs] Needs Gitbook homepage

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/cbelasticsearch#58]
We're missing a good landing page for the [Elasticsearch Gitbook](https://cbelasticsearch.ortusbooks.com). Take pointers from https://coldbox.ortusbooks.com.

**Comment by michaelborn** [comment]
Wait - it seems to be this Introduction page: https://cbelasticsearch.ortusbooks.com/introduction

So we just need to figure out how to map this to the Gitbook homepage then. (And remove it from the sidebar nav.)

**Comment by jclausen** [comment]
There seems to be a bug in the parsing of `book.json` ( https://docs.gitbook.com/integrations/github/content-configuration ) which is preventing the routing, theme, and menu from appearing correctly.  A support request with GitBook has been filed.

**Comment by michaelborn** [comment]
Any update on that support request, Jon? I'm curious as to the status on this.

**Comment by michaelborn** [comment]
Not sure when this changed, but I see the Gitbook homepage is working now.
