### ISSUE TITLE
[docs] Indexing Basics section out of date

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/cbelasticsearch#61]
We need to update [the index section of the docs](https://cbelasticsearch.ortusbooks.com/indexes#indexing-basics):

> In short, indexes have a higher overhead and make the aggregation of search results between types very more expensive. If it is desired that your application search interfaces return multiple entity or domain types, **then those should respresent distinctive types within a single index**, allowing them to be aggregated, sorted, and ordered in search results.

This is no longer valid in ES 7.0.

**Comment by jclausen** [comment]
The type is stored as a pseudo-private key now within the document ( _type ) but we should remove that to avoid confusion

________________________________

**Comment by michaelborn** [comment]
We don't necessarily need to change the way we handle types - keep ES >7 and ES <7 support. I'm just noting the need for up to date docs regarding index types. (And I'll try to get to this myself... nudge me if you like. )

**Comment by jclausen** [comment]
This is reslved in the most recent version of the Docs.  `type` support will be dropped in `v3`
