### ISSUE TITLE
Need better error message returns for "all shards failed"

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/cbelasticsearch#65]
Occasionally an error message returned from the Jest client is pretty useless - i.e. "all shards failed". If we can dig deeper into the error response from Elasticsearch, we can provide a much more useful message to the user/developer.

I tried the following in `SearchResult.cfc`, however I am having trouble testing it - I don't know how to programmatically generate an "all shards failed" error.

```js
// original "reason"
var reason = structKeyExists( arguments.properties, "error" ) ? " Reason: #arguments.properties.error.reason#" : "";

// new, more useful / deeper "reason"
if ( reason == "all shards failed" && structKeyExists( arguments.properties, "error" ) && structKeyExists( arguments.properties.error, "caused_by" ) ){
    reason = arguments.properties.error["caused_by"].reason;
}
// throw...
```

**Comment by jclausen** [comment]
I need to know which error is at issue. We have been displaying the `.error.reason`since commit `7f3cfce28ae416fc122b6cdac4f67ce013df832b` so I'm trying to determine where this error is bubbling up with the "All shards failed"

**Comment by michaelborn** [comment]
The point of this issue is that in some cases, `error.reason` is `"All shards failed"` - which is not really a _reason_ at all. My suggestion was to show the `caused_by` or `root_caused` reason if it exists in the error response, because it's likely to be a much more useful error message.

I don't have an example of this from `SearchResult.cfc`, but executing a `match` query against an index with a very small `indices.query.bool.max_clause_count` will throw the following:

```json
{
    "error": {
        "root_cause": [
            {
                "type": "query_shard_exception",
                "reason": "failed to create query: field expansion matches too many fields, limit: 50, got: 870",
                "index_uuid": "wYWodi1YS2-kRBiN_zjJTg",
                "index": "weat_3_3_0"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
...
}
```

**Comment by jclausen** [comment]
OK. I'm tracking now. Let me see if I can tweak that out a bit.
