### ISSUE TITLE
client.saveAll() does not properly handle errors if throwOnError=false

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/cbelasticsearch#68]
If one calls the `saveAll()` method without passing `throwOnError=true`, the HyperClient will actually cause an error on line 1121 because the expected `items` do not exist in the returned result.

https://github.com/coldbox-modules/cbox-elasticsearch/blob/development/modules/cbelasticsearch/models/io/HyperClient.cfc#L1121

So basically, if `throwOnError=true` is not passed, the Hyper client fails to handle errors whatsoever, and still attempts to loop over items even if they do not exist.

I wouldn't mind sending a small PR to fix this!

Suggested fix:

```js
param saveResult.items = []
```

**Comment by jclausen** [comment]
Resolved in commit c3f6a58
