### ISSUE TITLE
Hyperpool.cfc - variables.currentIndex[ nodeUsage ] is always 1

### ISSUE THREAD

**Issue by eppinger** [coldbox-modules/cbelasticsearch#71]
The structkey 'nodeUsage' in variables.currentIndexes in the function getAvailableNode() never exists.
It is a mixture between curentIndex and currentIndexes.

=> the round-robin didn't really working, if i understand this function correctly

**Comment by jclausen** [comment]
@eppinger I think you're correct. It looks like there's a mixed usage of `currentIndex` and `currentIndexes`. My bad.  I'll dig in to this today, and push up a fix.

**Comment by eppinger** [comment]
Thanks !

**Comment by jclausen** [comment]
No problem. I plan on bumping a patch release later today, after I make a few more updates and fixes to some of the Logstash functionality
