### ISSUE TITLE
[feat] Missing AliasBuilder.save() method

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/cbelasticsearch#80]
Seeing as we can run `getInstance( "Document@cbElasticsearch" ).new(...).save()`, and `getInstance( "IndexBuilder@cbElasticsearch" ).new(...).save()`, why can't we have `getInstance( "AliasBuilder@cbElasticsearch" ).new(...).save()`?

IMHO it's a little awkward to require passing the `AliasBuilder` instance in to `client.applyAliases()`, though I understand it would still be necessary for saving multiple aliases at once.

I would be happy to tackle this myself, by the way. :)

**Comment by jclausen** [comment]
Go for it!

________________________________
