### ISSUE TITLE
Document.setId() does not persist??

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/cbelasticsearch#83]
The `setId()` method call on the Document component doesn't seem to actually set `variables.id` in the component.

```js
application.wirebox.getInstance( "Document@CBElasticsearch" )
						.setIndex( "classes" )
						.setId( rc.id )
						.get()
```

Running this gives me the following error:

![Screenshot from 2021-04-25 20-51-30](https://user-images.githubusercontent.com/8106227/116078893-2b1a8c80-a665-11eb-97ac-130a74d6f5a6.png)

And yep, I confirmed that `rc.id` is a valid document ID. Changing to the following made the error "go away":

```js
application.wirebox.getInstance( "Document@CBElasticsearch" )
						.get(
							index = "classes",
							id = rc.id
						)
```

Has something changed on this? I scanned the `Document.cfc`, but I'm not seeing any `variables.id` nonsense... unless somehow the `reset` is being called before `get()` runs. :thinking:

**Comment by jclausen** [comment]
The above code should work because of the the following in the `get` method:

```
if( !structIsEmpty( arguments ) ){
	structAppend( variables, arguments, true );
}
```

Have you tried dumping `variables` at the point of execution?   Also, what engine?  Maybe there's a regression in `structIsEmpty` ?

**Comment by jclausen** [comment]
Also, which version of Elasticsearch are you testing on?

**Comment by jclausen** [comment]
Why try to retrieve it through the document, anyway?

`getInstance( "Client@cbElasticsearch" ) .get( id, index )` will return a `Document` object

**Comment by jclausen** [comment]
BTW, it does set `variables.id` but it's not used in the `get` method because the arguments scope is used. It's probably not a bad idea to add a `structAppend` _from_ the variables scope to the arguments scope if it's empty.  I don't think I've ever used a `Document` this way, since I always perform `get` actions through the client

**Comment by michaelborn** [comment]
Yes, it's a kinda weird way to perform a document get, but I was literally following [the first example in the CBElasticsearch docs](https://cbelasticsearch.ortusbooks.com/documents#retrieving-documents).

I haven't tried debugging yet, but I will. In Lucee 5.3.6+61 and Elasticsearch 7.6.2.

**Comment by michaelborn** [comment]
> BTW, it does set `variables.id` but it's not used in the `get` method because the arguments scope is used. It's probably not a bad idea to add a `structAppend` _from_ the variables scope to the arguments scope if it's empty. I don't think I've ever used a `Document` this way, since I always perform `get` actions through the client

Actually, it uses the `variables` scope and does a `structAppend()` to append the arguments to merge the two scopes before the get call.

**Comment by michaelborn** [comment]
Yep, something funky is going on with this.

See debug code:

```js
function get( string id, string index, string type ){
// see screenshot; shows three arguments with "Empty:null"
    writeDump( arguments );
    writeDump( variables.id ); // returns "string	218ABF62-5776-46D7-82E11AA55F8504C3"
    writeDump( isNull( variables.id ) ); // returns "false"

    if( !structIsEmpty( arguments ) ){
        structAppend( variables, arguments, true );
    }
    writeDump( isNull( variables.id ) ); // returns "true"
```

Looks like `structIsEmpty()` is returning "false" when it should be "true". I'll check in trycf.com.

![Screenshot from 2021-04-26 08-42-12](https://user-images.githubusercontent.com/8106227/116084445-cf9fcd00-a66b-11eb-830e-ce7392eeeba6.png)

**Comment by jclausen** [comment]
Do you have full null support turned on?  That could cause the issue you're seeing.

**Comment by jclausen** [comment]
We should probably change that code to support that feature, though - by looping the keys instead of `structIsEmpty`

**Comment by michaelborn** [comment]
> Do you have full null support turned on? That could cause the issue you're seeing.

I'll take a look. This is a vanilla install of Lucee 5.3.6, I haven't purposely enabled any settings.

The following returns `No` in all versions of Lucee and CF: https://trycf.com/scratch-pad/gist/549edd013046901e6fc1a9d3c83cef56

**Comment by michaelborn** [comment]
Just confirmed that Null Support is only set to "Partial support". i.e. full null support is not enabled.
![Screenshot from 2021-04-26 08-55-20](https://user-images.githubusercontent.com/8106227/116085836-3a053d00-a66d-11eb-9bd8-846d1900c925.png)

**Comment by jclausen** [comment]
It also returns "No" in ACF versions.  https://trycf.com/gist/628e8b5fab0454dc506a6a4a2a0366e6/acf2018?theme=monokai

I'm not sure how we never caught this before, but it will need to be patched

**Comment by michaelborn** [comment]
I can try to send up a PR when I'm not "at work". :smile:
