### ISSUE TITLE
Bug: Logstash Appender fails if tagContext "Template" file does not exist.

### ISSUE THREAD

**Issue by michaelborn** [coldbox-modules/cbelasticsearch#87]
Try to run this code on ACF:

```js
javaCast( "integer", 0 );
```

In ACF, that one-liner will create an exception where `tagContext[1].TEMPLATE` is actually `"eg"`. This obviously makes no sense, but it seems we may need to safely handle cases where the referenced `template` file does not exist.

See screenshot:

![Screenshot from 2021-08-12 13-39-53](https://user-images.githubusercontent.com/8106227/129243198-6a1e1479-ed54-4a6d-abbc-639cdebbe342.png)

I could try to add a workaround, but I'm not sure what should happen here. I would think downstream stuff like stachebox would expect the source code keys to be populated in the error log JSON.

**Comment by jclausen** [comment]
A file existence check is now present in LogStashAppender, which should handle this issue
